// Travel Packages Data for the new section
export const TRAVEL_PACKAGES_DATA = [
  {
    destination_id: 1,
    destination_name: "Thailand",
    category: "international",
    description:
      "Explore vibrant beaches, bustling markets, and rich culture of Thailand.",
    thumbnail_image: "/assets/png/thailand.jpg",
    hero_image: "/assets/png/thailand-hero.jpg",
    reviews: [
      {
        id: 1,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Sri Lanka (Jul 2024)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt: "Smiling woman with dark wavy hair wearing red top",
        rating: 4.6,
      },
      {
        id: 2,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Coorg (Oct 2025)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt: "Young man with curly hair wearing dark hat and t-shirt",
        rating: 4.6,
      },
      {
        id: 3,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Coorg (Oct 2025)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt:
          "Smiling Black man with shaved head wearing green and white patterned shirt",
        rating: 4.6,
      },
      {
        id: 1,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Sri Lanka (Jul 2024)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt: "Smiling woman with dark wavy hair wearing red top",
        rating: 4.6,
      },
      {
        id: 2,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Coorg (Oct 2025)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt: "Young man with curly hair wearing dark hat and t-shirt",
        rating: 4.6,
      },
      {
        id: 3,
        description:
          "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see.",
        name: "JAMES THOMAS",
        location: "Coorg (Oct 2025)",
        profileImage: "/assets/png/profile-1.jpg",
        imageAlt:
          "Smiling Black man with shaved head wearing green and white patterned shirt",
        rating: 4.6,
      },
    ],
    trips: [
      {
        id: 1,
        title: "Bangkok & Pattaya Special",
        duration: "6D-5N",
        price: 35000,
        originalPrice: 40000,
        discountAmount: 5000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],

        availableDates: ["jun25", "jul25", "aug25"],
        features: ["city-life", "nightlife", "beach"],
        customizable: true,
        badge: { type: "", text: "" },
      },
      {
        id: 2,
        title: "Phuket & Krabi Escape",
        duration: "7D-6N",
        price: 42000,
        originalPrice: 45000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jul25", "aug25", "sep25"],
        features: ["beach", "island", "water-sports"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 2,
    destination_name: "Europe",
    category: "international",
    description:
      "Experience the charm of European cities, culture, and history.",
    thumbnail_image: "/assets/png/europe.jpg",
    hero_image: "/assets/png/europe-hero.jpg",
    reviews: [
      {
        name: "Neha Patel",
        description:
          "The Swiss Alps were breathtaking! Loved the train journeys.",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 3,
        title: "European Grand Tour",
        duration: "12D-11N",
        price: 125000,
        // originalPrice: 130000,
        // discountAmount: 5000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["sep25", "oct25", "nov25"],
        features: ["culture", "history", "architecture"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 3,
    destination_name: "Indonesia",
    category: "international",
    description:
      "Discover tropical paradise with temples, rice fields, and beaches.",
    thumbnail_image: "/assets/png/indonesia.jpg",
    hero_image: "/assets/png/indonesia-hero.jpg",
    reviews: [
      {
        name: "Simran Joshi",
        description: "Bali was magical, especially the temples and beaches.",
        rating: 4.7,
      },
    ],
    trips: [
      {
        id: 4,
        title: "Bali Temple & Beach Tour",
        duration: "7D-6N",
        price: 52000,
        originalPrice: 55000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jul25", "aug25", "sep25"],
        features: ["temple", "beach", "culture"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 4,
    destination_name: "Vietnam",
    category: "international",
    description:
      "Explore rich history, delicious cuisine, and stunning landscapes.",
    thumbnail_image: "/assets/png/vietnam.jpg",
    hero_image: "/assets/png/vietnam-hero.jpg",
    reviews: [
      {
        name: "Rajesh Kumar",
        description:
          "Vietnam's food scene is incredible! Loved the street food.",
        rating: 4.6,
      },
    ],
    trips: [
      {
        id: 5,
        title: "Vietnam Cultural Journey",
        duration: "8D-7N",
        price: 48000,
        originalPrice: 50000,
        discountAmount: 2000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["aug25", "sep25", "oct25"],
        features: ["culture", "food", "history"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 5,
    destination_name: "Egypt",
    category: "international",
    description: "Uncover ancient mysteries, pyramids, and the Nile River.",
    thumbnail_image: "/assets/png/egypt.jpg",
    hero_image: "/assets/png/egypt-hero.jpg",
    reviews: [
      {
        name: "Priya Nair",
        description: "The pyramids are absolutely magnificent! A must-visit.",
        rating: 4.8,
      },
    ],
    trips: [
      {
        id: 6,
        title: "Egypt Pyramids & Nile",
        duration: "10D-9N",
        price: 75000,
        originalPrice: 78000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["oct25", "nov25", "dec25"],
        features: ["history", "pyramids", "nile-cruise"],
        customizable: true,
        badge: { type: "historical", text: "Historical Tour" },
      },
    ],
  },
  {
    destination_id: 6,
    destination_name: "USA",
    category: "international",
    description: "Experience the American dream, from coast to coast.",
    thumbnail_image: "/assets/png/usa.jpg",
    hero_image: "/assets/png/usa-hero.jpg",
    reviews: [
      {
        name: "Arjun Singh",
        description: "New York and LA were incredible! Loved the diversity.",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 7,
        title: "USA Coast to Coast",
        duration: "15D-14N",
        price: 150000,
        originalPrice: 155000,
        discountAmount: 5000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["nov25", "dec25", "jan26"],
        features: ["cities", "culture", "adventure"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 7,
    destination_name: "Canada",
    category: "international",
    description:
      "Discover natural beauty, friendly people, and outdoor adventures.",
    thumbnail_image: "/assets/png/canada.jpg",
    hero_image: "/assets/png/canada-hero.jpg",
    reviews: [
      {
        name: "Meera Iyer",
        description:
          "Canada's nature is breathtaking! Loved Banff National Park.",
        rating: 4.7,
      },
    ],
    trips: [
      {
        id: 8,
        title: "Canadian Rockies Adventure",
        duration: "14D-13N",
        price: 135000,
        originalPrice: 138000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["mountains", "nature", "adventure"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 8,
    destination_name: "Japan",
    category: "international",
    description: "Experience the perfect blend of tradition and modernity.",
    thumbnail_image: "/assets/png/japan.jpg",
    hero_image: "/assets/png/japan-hero.jpg",
    reviews: [
      {
        name: "Kavya Reddy",
        description:
          "Japan is amazing! Cherry blossoms and temples were magical.",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 9,
        title: "Japan Cherry Blossom",
        duration: "14D-13N",
        price: 180000,
        originalPrice: 185000,
        discountAmount: 5000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["mar26", "apr26", "may26"],
        features: ["cherry-blossom", "culture", "technology"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 9,
    destination_name: "Australia",
    category: "international",
    description:
      "Explore the land down under with unique wildlife and landscapes.",
    thumbnail_image: "/assets/png/australia.jpg",
    hero_image: "/assets/png/australia-hero.jpg",
    reviews: [
      {
        name: "Vikram Malhotra",
        description:
          "Sydney Opera House and Great Barrier Reef were incredible!",
        rating: 4.8,
      },
    ],
    trips: [
      {
        id: 10,
        title: "Australia Wildlife & Reef",
        duration: "16D-15N",
        price: 200000,
        originalPrice: 205000,
        discountAmount: 5000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["sep25", "oct25", "nov25"],
        features: ["wildlife", "reef", "cities"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 10,
    destination_name: "Singapore",
    category: "international",
    description:
      "Modern city-state with diverse culture and amazing attractions.",
    thumbnail_image: "/assets/png/singapore.jpg",
    hero_image: "/assets/png/singapore-hero.jpg",
    reviews: [
      {
        name: "Ananya Sharma",
        description:
          "Singapore is so clean and modern! Gardens by the Bay was stunning.",
        rating: 4.6,
      },
    ],
    trips: [
      {
        id: 11,
        title: "Singapore City Explorer",
        duration: "5D-4N",
        price: 55000,
        originalPrice: 58000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["city", "culture", "shopping"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 11,
    destination_name: "Maldives",
    category: "international",
    description:
      "Luxury resorts, white sandy beaches, and crystal-clear waters.",
    thumbnail_image: "/assets/png/maldives.jpg",
    hero_image: "/assets/png/maldives-hero.jpg",
    reviews: [
      {
        name: "Priya Nair",
        description: "Best honeymoon destination with stunning water villas.",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 12,
        title: "Maldives Luxury Escape",
        duration: "5D-4N",
        price: 95000,
        // originalPrice: 98000,
        // discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["aug25", "sep25", "oct25"],
        features: ["luxury", "beach", "water-villa"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 12,
    destination_name: "Dubai",
    category: "international",
    description: "Desert safaris, shopping malls, and futuristic skyscrapers.",
    thumbnail_image: "/assets/png/dubai.jpg",
    hero_image: "/assets/png/dubai-hero.jpg",
    reviews: [
      {
        name: "Arjun Singh",
        description: "Dubai is a shopping paradise with incredible nightlife.",
        rating: 4.5,
      },
    ],
    trips: [
      {
        id: 13,
        title: "Dubai Shopping Festival",
        duration: "6D-5N",
        price: 60000,
        originalPrice: 63000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["dec25", "jan26", "feb26"],
        features: ["shopping", "luxury", "desert"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 13,
    destination_name: "Kerala",
    category: "domestic",
    description: "God's own country with backwaters, beaches, and ayurveda.",
    thumbnail_image: "/assets/png/kerala.jpg",
    hero_image: "/assets/png/kerala-hero.jpg",
    reviews: [
      {
        name: "Ravi Verma",
        description: "Kerala's backwaters are so peaceful and beautiful.",
        rating: 4.8,
      },
    ],
    trips: [
      {
        id: 14,
        title: "Kerala Backwaters & Ayurveda",
        duration: "5D-4N",
        price: 25000,
        originalPrice: 28000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["backwaters", "ayurveda", "nature"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 14,
    destination_name: "Goa",
    category: "domestic",
    description:
      "Sun, sand, and sea with Portuguese heritage and vibrant nightlife.",
    thumbnail_image: "/assets/png/goa.jpg",
    hero_image: "/assets/png/goa-hero.jpg",
    reviews: [
      {
        name: "Sofia Khan",
        description: "Goa beaches are perfect for relaxation and partying!",
        rating: 4.7,
      },
    ],
    trips: [
      {
        id: 15,
        title: "Goa Beach & Party",
        duration: "4D-3N",
        price: 22000,
        originalPrice: 25000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["beach", "party", "heritage"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 15,
    destination_name: "Rajasthan",
    category: "domestic",
    description: "Land of kings with magnificent palaces, forts, and desert.",
    thumbnail_image: "/assets/png/rajasthan.jpg",
    hero_image: "/assets/png/rajasthan-hero.jpg",
    reviews: [
      {
        name: "Neha Patel",
        description: "Rajasthan's palaces are like fairy tales come true!",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 16,
        title: "Rajasthan Royal Heritage",
        duration: "6D-5N",
        price: 28000,
        originalPrice: 31000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["oct25", "nov25", "dec25"],
        features: ["heritage", "palace", "culture"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 16,
    destination_name: "Himachal Pradesh",
    category: "domestic",
    description:
      "Himalayan paradise with snow-capped peaks and adventure sports.",
    thumbnail_image: "/assets/png/himachal.jpg",
    hero_image: "/assets/png/himachal-hero.jpg",
    reviews: [
      {
        name: "Vikram Malhotra",
        description: "Manali and Shimla are perfect for mountain lovers!",
        rating: 4.8,
      },
    ],
    trips: [
      {
        id: 17,
        title: "Himachal Mountain Adventure",
        duration: "7D-6N",
        price: 30000,
        originalPrice: 33000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["mountains", "adventure", "nature"],
        customizable: true,
        badge: { type: "", text: "" },
      },
    ],
  },
  {
    destination_id: 17,
    destination_name: "Ladakh",
    category: "domestic",
    description:
      "High-altitude deserts, monasteries, and breathtaking landscapes.",
    thumbnail_image: "/assets/png/ladakh.jpg",
    hero_image: "/assets/png/ladakh-hero.jpg",
    reviews: [
      {
        name: "Ravi Verma",
        description: "Ladakh's mountains are magical, truly heaven on earth.",
        rating: 5.0,
      },
    ],
    trips: [
      {
        id: 18,
        title: "Leh & Nubra Valley Adventure",
        duration: "8D-7N",
        price: 55000,
        originalPrice: 58000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25", "sep25"],
        features: ["mountain", "adventure", "culture"],
        customizable: false,
        badge: { type: "hot", text: "Trending" },
      },
    ],
  },
  {
    destination_id: 18,
    destination_name: "Kashmir",
    category: "domestic",
    description: "Paradise on earth with beautiful valleys and houseboats.",
    thumbnail_image: "/assets/png/kashmir.jpg",
    hero_image: "/assets/png/kashmir-hero.jpg",
    reviews: [
      {
        name: "Priya Nair",
        description: "Kashmir is absolutely stunning! Dal Lake is magical.",
        rating: 4.9,
      },
    ],
    trips: [
      {
        id: 19,
        title: "Kashmir Valley & Houseboat",
        duration: "8D-7N",
        price: 35000,
        originalPrice: 38000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["jun25", "jul25", "aug25"],
        features: ["valley", "houseboat", "nature"],
        customizable: true,
        badge: { type: "romantic", text: "Romantic Getaway" },
      },
    ],
  },
  {
    destination_id: 19,
    destination_name: "Lonavala",
    category: "weekend",
    description: "Perfect weekend getaway with scenic views and adventure.",
    thumbnail_image: "/assets/png/lonavala.jpg",
    hero_image: "/assets/png/lonavala-hero.jpg",
    reviews: [
      {
        name: "Ananya Sharma",
        description:
          "Perfect weekend escape from Mumbai! Loved the viewpoints.",
        rating: 4.6,
      },
    ],
    trips: [
      {
        id: 20,
        title: "Lonavala Weekend Escape",
        duration: "2D-1N",
        price: 8000,
        originalPrice: 11000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["every-weekend"],
        features: ["weekend", "nature", "adventure"],
        customizable: true,
        badge: { type: "weekend", text: "Weekend Special" },
      },
    ],
  },
  {
    destination_id: 20,
    destination_name: "Mahabaleshwar",
    category: "weekend",
    description:
      "Queen of hill stations with strawberry farms and scenic beauty.",
    thumbnail_image: "/assets/png/mahabaleshwar.jpg",
    hero_image: "/assets/png/mahabaleshwar-hero.jpg",
    reviews: [
      {
        name: "Rajesh Kumar",
        description:
          "Mahabaleshwar is so peaceful! Strawberry picking was fun.",
        rating: 4.7,
      },
    ],
    trips: [
      {
        id: 21,
        title: "Mahabaleshwar Strawberry Tour",
        duration: "2D-1N",
        price: 9500,
        originalPrice: 12000,
        discountAmount: 3000,
        image: "/assets/png/banner1.jpg",
        other_images: [
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
          "/assets/png/banner1.jpg",
        ],
        availableDates: ["every-weekend"],
        features: ["weekend", "strawberry", "nature"],
        customizable: true,
        badge: { type: "weekend", text: "Weekend Special" },
      },
    ],
  },
];

// export const TRAVEL_PACKAGES_DATA = [
//   {
//     id: 1,
//     title: "Beach & Sands",
//     destination: "beach",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["12 Jul", "25 Jul", "8 Aug", "13 Aug", "21 Aug", "5 Sep", "18 Sep"],
//     features: ["beach", "relaxation", "water-sports"],
//     customizable: false
//   },
//   {
//     id: 2,
//     title: "Summer Fun",
//     destination: "beach",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["15 Jun", "28 Jun", "12 Jul", "25 Jul", "8 Aug"],
//     features: ["beach", "adventure", "family"],
//     customizable: true,
//     badge: { type: "", text: "" }
//   },
//   {
//     id: 3,
//     title: "Crystal Waters",
//     destination: "island",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["10 Jul", "22 Jul", "5 Aug", "18 Aug", "2 Sep", "15 Sep"],
//     features: ["island", "luxury", "water-activities"],
//     customizable: false
//   },
//   {
//     id: 4,
//     title: "Mountain Escape",
//     destination: "nature",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["8 Jul", "20 Jul", "3 Aug", "16 Aug", "30 Aug", "12 Sep"],
//     features: ["nature", "adventure", "outdoor"],
//     customizable: true,
//     badge: { type: "", text: "" }
//   },
//   {
//     id: 5,
//     title: "Desert Adventure",
//     destination: "desert",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["14 Jul", "27 Jul", "10 Aug", "24 Aug", "7 Sep"],
//     features: ["desert", "adventure", "culture"],
//     customizable: true
//   },
//   {
//     id: 6,
//     title: "Forest Retreat",
//     destination: "forest",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["18 Jul", "1 Aug", "15 Aug", "28 Aug", "10 Sep"],
//     features: ["forest", "wildlife", "eco-tourism"],
//     customizable: true,
//     badge: { type: "", text: "" }
//   },
//   {
//     id: 7,
//     title: "City Lights",
//     destination: "urban",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["22 Jul", "5 Aug", "19 Aug", "2 Sep", "16 Sep"],
//     features: ["urban", "culture", "shopping"],
//     customizable: true
//   },
//   {
//     id: 8,
//     title: "Heritage Trail",
//     destination: "heritage",
//     duration: "7D-8N",
//     price: "Rs. 23,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["25 Jul", "8 Aug", "22 Aug", "5 Sep", "19 Sep"],
//     features: ["heritage", "history", "architecture"],
//     customizable: false
//   },
//   {
//     id: 9,
//     title: "Luxury Maldives",
//     destination: "island",
//     duration: "10D-11N",
//     price: "Rs. 85,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["20 Jul", "3 Aug", "17 Aug", "31 Aug", "14 Sep"],
//     features: ["island", "luxury", "water-activities", "spa"],
//     customizable: true
//   },
//   {
//     id: 10,
//     title: "Himalayan Trek",
//     destination: "nature",
//     duration: "12D-13N",
//     price: "Rs. 45,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["15 Jul", "29 Jul", "12 Aug", "26 Aug", "9 Sep"],
//     features: ["nature", "adventure", "trekking", "mountains"],
//     customizable: true
//   },
//   {
//     id: 11,
//     title: "Goa Beach Party",
//     destination: "beach",
//     duration: "5D-6N",
//     price: "Rs. 18,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["25 Jul", "8 Aug", "22 Aug", "5 Sep", "19 Sep"],
//     features: ["beach", "party", "nightlife", "water-sports"],
//     customizable: true
//   },
//   {
//     id: 12,
//     title: "Kerala Backwaters",
//     destination: "nature",
//     duration: "6D-7N",
//     price: "Rs. 28,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["18 Jul", "1 Aug", "15 Aug", "29 Aug", "12 Sep"],
//     features: ["nature", "backwaters", "ayurveda", "houseboat"],
//     customizable: false
//   },
//   {
//     id: 13,
//     title: "Rajasthan Royal",
//     destination: "heritage",
//     duration: "8D-9N",
//     price: "Rs. 35,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["12 Jul", "26 Jul", "9 Aug", "23 Aug", "6 Sep"],
//     features: ["heritage", "culture", "palace", "desert"],
//     customizable: true
//   },
//   {
//     id: 14,
//     title: "Andaman Islands",
//     destination: "island",
//     duration: "9D-10N",
//     price: "Rs. 52,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["16 Jul", "30 Jul", "13 Aug", "27 Aug", "10 Sep"],
//     features: ["island", "beach", "water-activities", "history"],
//     customizable: true
//   },
//   {
//     id: 15,
//     title: "Ladakh Adventure",
//     destination: "nature",
//     duration: "11D-12N",
//     price: "Rs. 48,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["10 Jul", "24 Jul", "7 Aug", "21 Aug", "4 Sep"],
//     features: ["nature", "adventure", "mountains", "buddhism"],
//     customizable: true
//   },
//   {
//     id: 16,
//     title: "Mumbai City Tour",
//     destination: "urban",
//     duration: "4D-5N",
//     price: "Rs. 15,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["28 Jul", "11 Aug", "25 Aug", "8 Sep", "22 Sep"],
//     features: ["urban", "culture", "shopping", "food"],
//     customizable: false
//   },
//   {
//     id: 17,
//     title: "Varanasi Spiritual",
//     destination: "heritage",
//     duration: "5D-6N",
//     price: "Rs. 22,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["14 Jul", "28 Jul", "11 Aug", "25 Aug", "8 Sep"],
//     features: ["heritage", "spiritual", "culture", "ganges"],
//     customizable: true
//   },
//   {
//     id: 18,
//     title: "Coorg Coffee Trail",
//     destination: "nature",
//     duration: "6D-7N",
//     price: "Rs. 25,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["20 Jul", "3 Aug", "17 Aug", "31 Aug", "14 Sep"],
//     features: ["nature", "coffee", "plantations", "adventure"],
//     customizable: true
//   },
//   {
//     id: 19,
//     title: "Pondicherry French",
//     destination: "heritage",
//     duration: "5D-6N",
//     price: "Rs. 20,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["22 Jul", "5 Aug", "19 Aug", "2 Sep", "16 Sep"],
//     features: ["heritage", "french", "beach", "culture"],
//     customizable: false
//   },
//   {
//     id: 20,
//     title: "Shimla Hill Station",
//     destination: "nature",
//     duration: "7D-8N",
//     price: "Rs. 30,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["17 Jul", "31 Jul", "14 Aug", "28 Aug", "11 Sep"],
//     features: ["nature", "hills", "adventure", "toy-train"],
//     customizable: true
//   },
//   {
//     id: 21,
//     title: "Udaipur Lake City",
//     destination: "heritage",
//     duration: "6D-7N",
//     price: "Rs. 32,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["19 Jul", "2 Aug", "16 Aug", "30 Aug", "13 Sep"],
//     features: ["heritage", "lakes", "palace", "romance"],
//     customizable: true
//   },
//   {
//     id: 22,
//     title: "Rishikesh Yoga",
//     destination: "nature",
//     duration: "8D-9N",
//     price: "Rs. 28,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["13 Jul", "27 Jul", "10 Aug", "24 Aug", "7 Sep"],
//     features: ["nature", "yoga", "adventure", "ganges"],
//     customizable: true
//   },
//   {
//     id: 23,
//     title: "Darjeeling Tea",
//     destination: "nature",
//     duration: "7D-8N",
//     price: "Rs. 35,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["21 Jul", "4 Aug", "18 Aug", "1 Sep", "15 Sep"],
//     features: ["nature", "tea", "mountains", "toy-train"],
//     customizable: false
//   },
//   {
//     id: 24,
//     title: "Agra Taj Mahal",
//     destination: "heritage",
//     duration: "4D-5N",
//     price: "Rs. 18,000/-",
//     image: "/assets/png/banner1.jpg",
//     availableDates: ["26 Jul", "9 Aug", "23 Aug", "6 Sep", "20 Sep"],
//     features: ["heritage", "taj-mahal", "history", "culture"],
//     customizable: true
//   }
// ];

// Filter Options for the travel packages section
export const FILTER_OPTIONS = {
  destinations: [
    { value: "Thailand", label: "Thailand" },
    { value: "Europe", label: "Europe" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Egypt", label: "Egypt" },
    { value: "USA", label: "USA" },
    { value: "Canada", label: "Canada" },
    { value: "Japan", label: "Japan" },
    { value: "Australia", label: "Australia" },
    { value: "Singapore", label: "Singapore" },
    { value: "Maldives", label: "Maldives" },
    { value: "Dubai", label: "Dubai" },
    { value: "Kerala", label: "Kerala" },
    { value: "Goa", label: "Goa" },
    { value: "Rajasthan", label: "Rajasthan" },
    { value: "Himachal Pradesh", label: "Himachal Pradesh" },
    { value: "Ladakh", label: "Ladakh" },
    { value: "Kashmir", label: "Kashmir" },
    { value: "Lonavala", label: "Lonavala" },
    { value: "Mahabaleshwar", label: "Mahabaleshwar" },
  ],
  destinationType: [
    { value: "international", label: "International" },
    { value: "domestic", label: "Domestic" },
    { value: "weekend", label: "Weekend" }
  ],
  dates: [
    { value: "jun25", label: "June 2025" },
    { value: "jul25", label: "July 2025" },
    { value: "aug25", label: "August 2025" },
    { value: "sep25", label: "September 2025" },
    { value: "oct25", label: "October 2025" },
    { value: "nov25", label: "November 2025" },
    { value: "dec25", label: "December 2025" },
    { value: "jan26", label: "January 2026" },
    { value: "feb26", label: "February 2026" },
    { value: "mar26", label: "March 2026" },
    { value: "apr26", label: "April 2026" },
    { value: "may26", label: "May 2026" },
  ],
  features: [
    { value: "beach", label: "Beach" },
    { value: "mountain", label: "Mountain" },
    { value: "culture", label: "Culture" },
    { value: "adventure", label: "Adventure" },
    { value: "luxury", label: "Luxury" },
    { value: "heritage", label: "Heritage" },
    { value: "nature", label: "Nature" },
    { value: "city-life", label: "City Life" },
    { value: "nightlife", label: "Nightlife" },
    { value: "island", label: "Island" },
    { value: "water-sports", label: "Water Sports" },
    { value: "shopping", label: "Shopping" },
    { value: "desert", label: "Desert" },
    { value: "temple", label: "Temple" },
    { value: "backwaters", label: "Backwaters" },
    { value: "ayurveda", label: "Ayurveda" },
    { value: "party", label: "Party" },
    { value: "palace", label: "Palace" },
    { value: "valley", label: "Valley" },
    { value: "houseboat", label: "Houseboat" },
    { value: "weekend", label: "Weekend" },
    { value: "strawberry", label: "Strawberry" },
  ],
  sort: [
    { value: "default", label: "Default" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
    { value: "duration", label: "Duration" },
    { value: "name", label: "Name" },
  ],

};

// Date tabs for filtering
export const DATE_TABS = [
  { id: "all", label: "All" },
  { id: "jun25", label: "June 2025" },
  { id: "jul25", label: "July 2025" },
  { id: "aug25", label: "August 2025" },
  { id: "sep25", label: "September 2025" },
  { id: "oct25", label: "October 2025" },
  { id: "nov25", label: "November 2025" },
  { id: "dec25", label: "December 2025" },
  { id: "jan26", label: "January 2026" },
  { id: "feb26", label: "February 2026" },
  { id: "mar26", label: "March 2026" },
  { id: "apr26", label: "April 2026" },
  { id: "may26", label: "May 2026" },
];
